/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.developer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StudentMessageOutput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6183167848339825321L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StudentMessageOutput\",\"namespace\":\"io.confluent.developer\",\"fields\":[{\"name\":\"uuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"consumerName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StudentMessageOutput> ENCODER =
      new BinaryMessageEncoder<StudentMessageOutput>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StudentMessageOutput> DECODER =
      new BinaryMessageDecoder<StudentMessageOutput>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StudentMessageOutput> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StudentMessageOutput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StudentMessageOutput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StudentMessageOutput>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StudentMessageOutput to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StudentMessageOutput from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StudentMessageOutput instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StudentMessageOutput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String uuid;
   private java.lang.String consumerName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StudentMessageOutput() {}

  /**
   * All-args constructor.
   * @param uuid The new value for uuid
   * @param consumerName The new value for consumerName
   */
  public StudentMessageOutput(java.lang.String uuid, java.lang.String consumerName) {
    this.uuid = uuid;
    this.consumerName = consumerName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uuid;
    case 1: return consumerName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uuid = value$ != null ? value$.toString() : null; break;
    case 1: consumerName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return The value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }



  /**
   * Gets the value of the 'consumerName' field.
   * @return The value of the 'consumerName' field.
   */
  public java.lang.String getConsumerName() {
    return consumerName;
  }



  /**
   * Creates a new StudentMessageOutput RecordBuilder.
   * @return A new StudentMessageOutput RecordBuilder
   */
  public static io.confluent.developer.StudentMessageOutput.Builder newBuilder() {
    return new io.confluent.developer.StudentMessageOutput.Builder();
  }

  /**
   * Creates a new StudentMessageOutput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StudentMessageOutput RecordBuilder
   */
  public static io.confluent.developer.StudentMessageOutput.Builder newBuilder(io.confluent.developer.StudentMessageOutput.Builder other) {
    if (other == null) {
      return new io.confluent.developer.StudentMessageOutput.Builder();
    } else {
      return new io.confluent.developer.StudentMessageOutput.Builder(other);
    }
  }

  /**
   * Creates a new StudentMessageOutput RecordBuilder by copying an existing StudentMessageOutput instance.
   * @param other The existing instance to copy.
   * @return A new StudentMessageOutput RecordBuilder
   */
  public static io.confluent.developer.StudentMessageOutput.Builder newBuilder(io.confluent.developer.StudentMessageOutput other) {
    if (other == null) {
      return new io.confluent.developer.StudentMessageOutput.Builder();
    } else {
      return new io.confluent.developer.StudentMessageOutput.Builder(other);
    }
  }

  /**
   * RecordBuilder for StudentMessageOutput instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StudentMessageOutput>
    implements org.apache.avro.data.RecordBuilder<StudentMessageOutput> {

    private java.lang.String uuid;
    private java.lang.String consumerName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.developer.StudentMessageOutput.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.consumerName)) {
        this.consumerName = data().deepCopy(fields()[1].schema(), other.consumerName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing StudentMessageOutput instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.developer.StudentMessageOutput other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.consumerName)) {
        this.consumerName = data().deepCopy(fields()[1].schema(), other.consumerName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.String getUuid() {
      return uuid;
    }


    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public io.confluent.developer.StudentMessageOutput.Builder setUuid(java.lang.String value) {
      validate(fields()[0], value);
      this.uuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public io.confluent.developer.StudentMessageOutput.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'consumerName' field.
      * @return The value.
      */
    public java.lang.String getConsumerName() {
      return consumerName;
    }


    /**
      * Sets the value of the 'consumerName' field.
      * @param value The value of 'consumerName'.
      * @return This builder.
      */
    public io.confluent.developer.StudentMessageOutput.Builder setConsumerName(java.lang.String value) {
      validate(fields()[1], value);
      this.consumerName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'consumerName' field has been set.
      * @return True if the 'consumerName' field has been set, false otherwise.
      */
    public boolean hasConsumerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'consumerName' field.
      * @return This builder.
      */
    public io.confluent.developer.StudentMessageOutput.Builder clearConsumerName() {
      consumerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StudentMessageOutput build() {
      try {
        StudentMessageOutput record = new StudentMessageOutput();
        record.uuid = fieldSetFlags()[0] ? this.uuid : (java.lang.String) defaultValue(fields()[0]);
        record.consumerName = fieldSetFlags()[1] ? this.consumerName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StudentMessageOutput>
    WRITER$ = (org.apache.avro.io.DatumWriter<StudentMessageOutput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StudentMessageOutput>
    READER$ = (org.apache.avro.io.DatumReader<StudentMessageOutput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.uuid);

    out.writeString(this.consumerName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.uuid = in.readString();

      this.consumerName = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.uuid = in.readString();
          break;

        case 1:
          this.consumerName = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










